export const GOVERNANCE_TARGET_TYPES = {
  POST: 'POST',
  REPLY: 'REPLY',
} as const;

export type GovernanceTargetType =
  (typeof GOVERNANCE_TARGET_TYPES)[keyof typeof GOVERNANCE_TARGET_TYPES];

export const GOVERNANCE_CASE_STATUS = {
  OPEN: 'OPEN',
  EMERGENCY: 'EMERGENCY',
  RESOLVED_VIOLATION: 'RESOLVED_VIOLATION',
  RESOLVED_NOT_VIOLATION: 'RESOLVED_NOT_VIOLATION',
} as const;

export type GovernanceCaseStatus =
  (typeof GOVERNANCE_CASE_STATUS)[keyof typeof GOVERNANCE_CASE_STATUS];

export const GOVERNANCE_ASSIGNMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  SUBMITTED: 'SUBMITTED',
  TIMED_OUT: 'TIMED_OUT',
  CASE_CLOSED: 'CASE_CLOSED',
} as const;

export type GovernanceAssignmentStatus =
  (typeof GOVERNANCE_ASSIGNMENT_STATUS)[keyof typeof GOVERNANCE_ASSIGNMENT_STATUS];

export const GOVERNANCE_DECISIONS = {
  VIOLATION: 'VIOLATION',
  NOT_VIOLATION: 'NOT_VIOLATION',
} as const;

export type GovernanceDecision =
  (typeof GOVERNANCE_DECISIONS)[keyof typeof GOVERNANCE_DECISIONS];

export const GOVERNANCE_HEALTH_LEVEL = {
  BANNED: 1,
  PENALIZED: 2,
  WARNING: 3,
  GOOD: 4,
} as const;

export type GovernanceHealthLevel =
  (typeof GOVERNANCE_HEALTH_LEVEL)[keyof typeof GOVERNANCE_HEALTH_LEVEL];

export const GOVERNANCE_MIN_DECISIVE_WEIGHT = 5;
export const GOVERNANCE_EMERGENCY_AFTER_HOURS = 48;
export const GOVERNANCE_ABANDON_AFTER_HOURS = 56;
export const GOVERNANCE_ASSIGNMENT_DEADLINE_MINUTES = 30;
export const GOVERNANCE_TIMEZONE = 'Asia/Shanghai';

export const GOVERNANCE_ERROR_CODES = {
  ACTIVE_CASE_EXISTS: 'ACTIVE_GOVERNANCE_CASE_EXISTS',
  NO_AVAILABLE_CASE: 'NO_AVAILABLE_GOVERNANCE_CASE',
  NOT_ELIGIBLE: 'GOVERNANCE_NOT_ELIGIBLE',
  QUOTA_EXHAUSTED: 'GOVERNANCE_QUOTA_EXHAUSTED',
  CASE_NOT_FOUND: 'GOVERNANCE_CASE_NOT_FOUND',
  ASSIGNMENT_NOT_FOUND: 'GOVERNANCE_ASSIGNMENT_NOT_FOUND',
  ALREADY_PARTICIPATED: 'GOVERNANCE_ALREADY_PARTICIPATED',
  CASE_NOT_READY_TO_RESOLVE: 'GOVERNANCE_CASE_NOT_READY_TO_RESOLVE',
} as const;
