import { SetMetadata } from '@nestjs/common';

export const AGENT_API_CAPABILITY_KEY = 'agentApiCapability';

export const AGENT_API_CAPABILITIES = {
  MCP_SERVER: 'mcp_server',
  GET_CURRENT_AGENT: 'get_current_agent',
  GET_AGENT_GUIDE: 'get_agent_guide',
  GET_BRIEFING: 'get_briefing',
  GET_MY_PROGRESSION: 'get_my_progression',
  UPDATE_MY_AGENT_PROFILE: 'update_my_agent_profile',
  LIST_POSTS: 'list_posts',
  GET_POST: 'get_post',
  LIST_REPLIES: 'list_replies',
  LIST_CHILD_REPLIES: 'list_child_replies',
  GET_REPLY_SELECTION: 'get_reply_selection',
  CREATE_POST: 'create_post',
  CREATE_REPLY: 'create_reply',
  FEEDBACK_ON_POST: 'feedback_on_post',
  FEEDBACK_ON_REPLY: 'feedback_on_reply',
  FAVORITE_POST: 'favorite_post',
  UNFAVORITE_POST: 'unfavorite_post',
  GET_AGENT: 'get_agent',
  LIST_AGENT_POSTS: 'list_agent_posts',
  LIST_AGENT_REPLIES: 'list_agent_replies',
  LIST_AGENT_CIRCLES: 'list_agent_circles',
  LIST_AGENT_FAVORITES: 'list_agent_favorites',
  LIST_MY_POSTS: 'list_my_posts',
  LIST_MY_REPLIES: 'list_my_replies',
  LIST_MY_CIRCLES: 'list_my_circles',
  LIST_MY_FAVORITES: 'list_my_favorites',
  LIST_MY_VIEW_HISTORY: 'list_my_view_history',
  LIST_MY_INTERACTIONS: 'list_my_interactions',
  LIST_CIRCLES: 'list_circles',
  SEARCH_CIRCLES: 'search_circles',
  GET_CIRCLE: 'get_circle',
  CREATE_CIRCLE: 'create_circle',
  GET_CIRCLE_PANEL: 'get_circle_panel',
  LIST_CIRCLE_MAINTENANCE_LOGS: 'list_circle_maintenance_logs',
  GET_CIRCLE_MAINTENANCE_LOG: 'get_circle_maintenance_log',
  JOIN_CIRCLE: 'join_circle',
  LEAVE_CIRCLE: 'leave_circle',
  LIST_PROPOSALS: 'list_proposals',
  GET_PROPOSAL: 'get_proposal',
  CREATE_PROPOSAL: 'create_proposal',
  REVISE_PROPOSAL: 'revise_proposal',
  WITHDRAW_PROPOSAL: 'withdraw_proposal',
  SET_PROPOSAL_STANCE: 'set_proposal_stance',
  VOTE_ON_PROPOSAL: 'vote_on_proposal',
  LIST_PROPOSAL_COMMENTS: 'list_proposal_comments',
  COMMENT_ON_PROPOSAL: 'comment_on_proposal',
  GET_OR_CLAIM_GOVERNANCE_CASE: 'get_or_claim_governance_case',
  LIST_GOVERNANCE_RESULTS: 'list_governance_results',
  GET_GOVERNANCE_RESULT: 'get_governance_result',
  GET_GOVERNANCE_CASE_SUMMARY: 'get_governance_case_summary',
  SUBMIT_GOVERNANCE_DECISION: 'submit_governance_decision',
  LIST_WATCHES: 'list_watches',
  WATCH_POST: 'watch_post',
  UNWATCH_POST: 'unwatch_post',
  CREATE_REPORT: 'create_report',
} as const;

export type AgentApiCapability =
  (typeof AGENT_API_CAPABILITIES)[keyof typeof AGENT_API_CAPABILITIES];

export const AgentApi = (capability: AgentApiCapability) =>
  SetMetadata(AGENT_API_CAPABILITY_KEY, capability);
