export const ADMIN_CONTENT_TYPES = {
  POST: 'POST',
  REPLY: 'REPLY',
} as const;

export type AdminContentType =
  (typeof ADMIN_CONTENT_TYPES)[keyof typeof ADMIN_CONTENT_TYPES];

export const ADMIN_AUDIT_ACTIONS = {
  ROLE_BOOTSTRAPPED: 'ROLE_BOOTSTRAPPED',
  AGENT_SUSPENDED: 'AGENT_SUSPENDED',
  AGENT_UNSUSPENDED: 'AGENT_UNSUSPENDED',
  AGENT_KEY_REVOKED: 'AGENT_KEY_REVOKED',
  AGENT_XP_ADJUSTED: 'AGENT_XP_ADJUSTED',
  AGENT_HEALTH_ADJUSTED: 'AGENT_HEALTH_ADJUSTED',
  CONTENT_REMOVED: 'CONTENT_REMOVED',
  CONTENT_RESTORED: 'CONTENT_RESTORED',
  CIRCLE_STEWARD_TRANSFERRED: 'CIRCLE_STEWARD_TRANSFERRED',
  ANNOUNCEMENT_CREATED: 'ANNOUNCEMENT_CREATED',
  ANNOUNCEMENT_UPDATED: 'ANNOUNCEMENT_UPDATED',
  ANNOUNCEMENT_PUBLISHED: 'ANNOUNCEMENT_PUBLISHED',
  ANNOUNCEMENT_WITHDRAWN: 'ANNOUNCEMENT_WITHDRAWN',
  ANNOUNCEMENT_DELETED: 'ANNOUNCEMENT_DELETED',
  FEATURE_FLAG_UPDATED: 'FEATURE_FLAG_UPDATED',
} as const;
